apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
spec:
  serviceSelector:
    matchLabels:
      type: public-lb
  loadBalancerIPs: true
  externalIPs: true
